// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hStats_C
NumericMatrix hStats_C(NumericMatrix locusdata, NumericVector strata);
RcppExport SEXP strataG_hStats_C(SEXP locusdataSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type locusdata(locusdataSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type strata(strataSEXP );
        NumericMatrix __result = hStats_C(locusdata, strata);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// colSumsC
NumericVector colSumsC(NumericMatrix mat);
RcppExport SEXP strataG_colSumsC(SEXP matSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP );
        NumericVector __result = colSumsC(mat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rowSumsC
NumericVector rowSumsC(NumericMatrix mat);
RcppExport SEXP strataG_rowSumsC(SEXP matSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP );
        NumericVector __result = rowSumsC(mat);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// colMeanC
double colMeanC(NumericMatrix data, int columnToAverage);
RcppExport SEXP strataG_colMeanC(SEXP dataSEXP, SEXP columnToAverageSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP );
        Rcpp::traits::input_parameter< int >::type columnToAverage(columnToAverageSEXP );
        double __result = colMeanC(data, columnToAverage);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rowMeanC
double rowMeanC(NumericMatrix data, int rowToAverage);
RcppExport SEXP strataG_rowMeanC(SEXP dataSEXP, SEXP rowToAverageSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP );
        Rcpp::traits::input_parameter< int >::type rowToAverage(rowToAverageSEXP );
        double __result = rowMeanC(data, rowToAverage);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// chi2H_C
double chi2H_C(NumericVector locusdata, NumericVector strata);
RcppExport SEXP strataG_chi2H_C(SEXP locusdataSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type locusdata(locusdataSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type strata(strataSEXP );
        double __result = chi2H_C(locusdata, strata);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// chi2D_C
double chi2D_C(NumericMatrix locusdata, NumericVector stratadata);
RcppExport SEXP strataG_chi2D_C(SEXP locusdataSEXP, SEXP stratadataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type locusdata(locusdataSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type stratadata(stratadataSEXP );
        double __result = chi2D_C(locusdata, stratadata);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// calcchi2
double calcchi2(NumericMatrix obsfreq, NumericVector rowSums, NumericVector colSums, int sizedata);
RcppExport SEXP strataG_calcchi2(SEXP obsfreqSEXP, SEXP rowSumsSEXP, SEXP colSumsSEXP, SEXP sizedataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type obsfreq(obsfreqSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type rowSums(rowSumsSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type colSums(colSumsSEXP );
        Rcpp::traits::input_parameter< int >::type sizedata(sizedataSEXP );
        double __result = calcchi2(obsfreq, rowSums, colSums, sizedata);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// fst_C
double fst_C(NumericMatrix locusdata, NumericVector strata);
RcppExport SEXP strataG_fst_C(SEXP locusdataSEXP, SEXP strataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type locusdata(locusdataSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type strata(strataSEXP );
        double __result = fst_C(locusdata, strata);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// gst_C
double gst_C(NumericVector strata, NumericMatrix hets);
RcppExport SEXP strataG_gst_C(SEXP strataSEXP, SEXP hetsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type strata(strataSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type hets(hetsSEXP );
        double __result = gst_C(strata, hets);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// gstDblPrime_C
double gstDblPrime_C(NumericVector strata, NumericMatrix hets);
RcppExport SEXP strataG_gstDblPrime_C(SEXP strataSEXP, SEXP hetsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type strata(strataSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type hets(hetsSEXP );
        double __result = gstDblPrime_C(strata, hets);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// gstPrimeHedrick_C
double gstPrimeHedrick_C(NumericVector strata, NumericMatrix hets, double gstestimate);
RcppExport SEXP strataG_gstPrimeHedrick_C(SEXP strataSEXP, SEXP hetsSEXP, SEXP gstestimateSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type strata(strataSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type hets(hetsSEXP );
        Rcpp::traits::input_parameter< double >::type gstestimate(gstestimateSEXP );
        double __result = gstPrimeHedrick_C(strata, hets, gstestimate);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// gstPrimeNei_C
double gstPrimeNei_C(NumericVector strata, NumericMatrix hets);
RcppExport SEXP strataG_gstPrimeNei_C(SEXP strataSEXP, SEXP hetsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type strata(strataSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type hets(hetsSEXP );
        double __result = gstPrimeNei_C(strata, hets);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// phist_C
double phist_C(NumericVector locusdata, NumericVector strata, NumericMatrix hapdist);
RcppExport SEXP strataG_phist_C(SEXP locusdataSEXP, SEXP strataSEXP, SEXP hapdistSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type locusdata(locusdataSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type strata(strataSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type hapdist(hapdistSEXP );
        double __result = phist_C(locusdata, strata, hapdist);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
