# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hStats_C <- function(locusdata, strata) {
    .Call('strataG_hStats_C', PACKAGE = 'strataG', locusdata, strata)
}

colSumsC <- function(mat) {
    .Call('strataG_colSumsC', PACKAGE = 'strataG', mat)
}

rowSumsC <- function(mat) {
    .Call('strataG_rowSumsC', PACKAGE = 'strataG', mat)
}

colMeanC <- function(data, columnToAverage) {
    .Call('strataG_colMeanC', PACKAGE = 'strataG', data, columnToAverage)
}

rowMeanC <- function(data, rowToAverage) {
    .Call('strataG_rowMeanC', PACKAGE = 'strataG', data, rowToAverage)
}

chi2H_C <- function(locusdata, strata) {
    .Call('strataG_chi2H_C', PACKAGE = 'strataG', locusdata, strata)
}

chi2D_C <- function(locusdata, stratadata) {
    .Call('strataG_chi2D_C', PACKAGE = 'strataG', locusdata, stratadata)
}

calcchi2 <- function(obsfreq, rowSums, colSums, sizedata) {
    .Call('strataG_calcchi2', PACKAGE = 'strataG', obsfreq, rowSums, colSums, sizedata)
}

fst_C <- function(locusdata, strata) {
    .Call('strataG_fst_C', PACKAGE = 'strataG', locusdata, strata)
}

gst_C <- function(strata, hets) {
    .Call('strataG_gst_C', PACKAGE = 'strataG', strata, hets)
}

gstDblPrime_C <- function(strata, hets) {
    .Call('strataG_gstDblPrime_C', PACKAGE = 'strataG', strata, hets)
}

gstPrimeHedrick_C <- function(strata, hets, gstestimate) {
    .Call('strataG_gstPrimeHedrick_C', PACKAGE = 'strataG', strata, hets, gstestimate)
}

gstPrimeNei_C <- function(strata, hets) {
    .Call('strataG_gstPrimeNei_C', PACKAGE = 'strataG', strata, hets)
}

phist_C <- function(locusdata, strata, hapdist) {
    .Call('strataG_phist_C', PACKAGE = 'strataG', locusdata, strata, hapdist)
}

